### ISSUE TITLE
403 Request Forbidden

### ISSUE THREAD

**Issue by Fox-in-the-Scaborough-Fair** [ChrisWu1997/onshape-cad-parser#2]
I try to add my access key and secret key correctly, but when I run `process.py` I get the request 403. I don't change the code. Do you know what happened? Thank you.

**Comment by rundiwu** [comment]
Hi,

Sorry for the late reply. Have you solved your problem? I re-cloned and re-tried the code (`python process.py --test`), and it works fine for me. Could you provide more information so I can possibly help?

**Comment by Fox-in-the-Scaborough-Fair** [comment]
Thank you for your reply! I have solved the problem by editting some propetites and it works well. Thank you!

**Comment by rundiwu** [comment]
Glad to hear that!
